Added 1630 Windows/Linux support
mafemergency/byond-tracy pull request #12
Opened 2024-02-13 10:18 UTC by Vladisvell

This PR adds 1630 support for windows and linux.
Due to procdef structure changes in 1624, i decided to add unk1 to procdef because bytecode moved 4 bytes forward and make procdef_legacy struct which is pre-1624 procdef structure.
Maybe there is a better way to implement backwards compatibility

Tested on windows, needs testing on linux.

2024-02-14 16:52 UTC, Cyberboss requested changes

2024-02-14 16:52 UTC, Cyberboss commented on prof.c
>  		if(procdef != NULL) {
```suggestion
		if(procdef_ptr!= NULL) {
```

2024-02-17 18:40 UTC, Bizzonium commented
Tested on Ubuntu 22.04, it works

2024-03-17 12:16 UTC, mafemergency commented
thanks for putting in the time and effort. i added to the script that automatically generates the per-version data so it will also grab the procdef's bytecode offset hopefully making future changes easier to integrate

2024-03-18 18:57 UTC, closed without merging